#!/bin/bash
mkdir docwebapp
cd docwebapp

cat << EOF > style.css
#header{
height:90px;
border-width:thin;
border-bottom: 1px solid #C0C0C0;
}

#body{
height:470px;
border-width:thin;
border-bottom: 1px solid #C0C0C0;
margin-left:10px;
margin-right:10px;
margin-top:10px;
}
#footer{
height:50px;
border-width:thin;
border-bottom: 1px solid #C0C0C0;
}
#location_text{
color:#323232;
margin-left:10px;
}
.button_green{
border:1px solid #34740e; -webkit-border-radius: 3px; -moz-border-radius: 3px;border-radius: 3px;font-size:12px;font-family:arial, helvetica, sans-serif; padding: 10px 10px 10px 10px; text-decoration:none; display:inline-block;text-shadow: -1px -1px 0 rgba(0,0,0,0.3);font-weight:bold; color: #FFFFFF;
 background-color: #4ba614; background-image: -webkit-gradient(linear, left top, left bottom, from(#4ba614), to(#008c00));
 background-image: -webkit-linear-gradient(top, #4ba614, #008c00);
 background-image: -moz-linear-gradient(top, #4ba614, #008c00);
 background-image: -ms-linear-gradient(top, #4ba614, #008c00);
 background-image: -o-linear-gradient(top, #4ba614, #008c00);
 background-image: linear-gradient(to bottom, #4ba614, #008c00);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#4ba614, endColorstr=#008c00);
}

.button_green:hover{
 border:1px solid #224b09;
 background-color: #36780f; background-image: -webkit-gradient(linear, left top, left bottom, from(#36780f), to(#005900));
 background-image: -webkit-linear-gradient(top, #36780f, #005900);
 background-image: -moz-linear-gradient(top, #36780f, #005900);
 background-image: -ms-linear-gradient(top, #36780f, #005900);
 background-image: -o-linear-gradient(top, #36780f, #005900);
 background-image: linear-gradient(to bottom, #36780f, #005900);filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr=#36780f, endColorstr=#005900);
}


EOF
cat << EOF > index.html
<html>
    <head><title>Hsenid Mobile Solutions</title>
    <link  rel="stylesheet" type="text/css"  href="style.css"></head>
    <body>

<div id="header">
  <h3><p style ="text-align:center; color:#A3CE3A;">Hsenid Mobile Solutions</p></h3>
  <p style ="text-align:center">Juju Charm Store</p>
</div>




<div id="body">
  <div style="float:left;">
    <p style="color:#4183C4; font-size:medium;"> You Have successfully installed Developer Bundle </p>
    <p style="color:#777777;"> See your Developer boundle go to
     <p id="location_text">user/ideamartBoundle</p>
     </p>
    <p style="color:#777777;"> See your Sample Applications
     <p id="location_text">user/ideamartBoundle/Samples</p>
     </p>
    <p style="color:#777777;"> See your Developer boundle go to
    <p id="location_text">user/ideamartBoundle</p>
    </p>
     <a class="button_green" href="http://devspace.hsenidmobile.com/guide/sms-api.php">Documentation</a>
  </div>

  <div style="float:right;">
  <img src="http://devspace.hsenidmobile.com/wp-content/uploads/2012/11/3nw.png" alt="Icon">

  </div>


</div>

<div id="footer">
  <p style ="text-align:center"> Copyright © 2014 by DevSpace. All Rights Reserved.
      Go Global</p>


</div>


</body>
</html>
EOF

mkdir WEB-INF
cd WEB-INF
cat << EOF > web.xml
<web-app id="simple" version="2.4">
    <welcome-file-list>
        <welcome-file>index.html</welcome-file>
    </welcome-file-list>
</web-app>
EOF

cd ..
pwd
jar cfM doc.war * 
chown -R sajith:doc.war

mv doc.war $CATALINA_HOME/webapps

